# Change these first
owner: ijazrushad # Your GitHub organization or username, where this repository lives
repo: ijaz-upptime # The name of this repository

sites:
  - name: Quizmaster
    url: https://quizmaster.shabox.mobi
  - name: Gamestar
    url: https://gamestar.shabox.mobi
  - name: Wordstar
    url: https://wordstar.shabox.mobi
  - name: AdPlay Website
    url: https://adplaytechnology.com
  - name: VU Website
    url: https://vumobile.biz
  - name: Baarta Website
    url: https://baarta.co
  - name: AdPlay RTB
    url: https://rtb.adplay-mobile.com
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: up.adplaytechnology.com
  # baseUrl: /ijaz-upptime
  logoUrl: https://adplaytechnology.com/wp-content/uploads/2023/10/Adplay-150x35-1.svg
  name: Technology Ltd
  introTitle: "This is a real time status monitor page for all **AdPlay Technology Ltd**, **VU Mobile Ltd** & **Baarta Technology Ltd ** services."
  introMessage: Website - [**AdPlay Technology Ltd**](https://adplaytechnology.com/) , [**Baarta Technology Ltd**](https://baarta.co) , [**VU Mobile Ltd**](https://vumobile.biz)
  navbar:
    - title: Status
      href: /
    - title: GitHub (Ijaz)
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
